#include "GCodeGenerator.h"
#include <QThread>
#include <QtConcurrent/QtConcurrent>
#include <QDebug>
#include <cmath>
#include <algorithm>

namespace ks {
namespace printing {

struct GCodeGenerator::Impl {
    // Helper to format numbers for G-code
    static QString fmt(double v, int prec = 3) {
        return QString::number(v, 'f', prec);
    }
    static QString fmtE(double v, int prec = 5) {
        return QString::number(v, 'f', prec);
    }
};

GCodeGenerator::GCodeGenerator(QObject* parent) : QObject(parent), d(std::make_unique<Impl>()) {}
GCodeGenerator::~GCodeGenerator() = default;

// ============================================================================
// Main Generation
// ============================================================================

QString GCodeGenerator::generateGCode(const SliceInfo& sliceInfo, const PrinterProfile& printer, const SliceSettings& settings) {
    return generateFromLayers(sliceInfo.slices, printer, settings, sliceInfo.boundingBox);
}

QString GCodeGenerator::generateFromLayers(const LayerSlices& slices, const PrinterProfile& printer, const SliceSettings& settings,
                                            const BoundingBox& bounds) {
    QString gcode;
    resetState();
    m_totalLayers = slices.size();

    // Header
    gcode += generateHeader(printer, settings, bounds);
    gcode += "\n";

    // Startup
    gcode += generateStartup(printer, settings);
    gcode += "\n";

    // Layers
    for (size_t i = 0; i < slices.size(); ++i) {
        m_currentLayer = static_cast<int>(i);
        if (i > 0) {
            gcode += generateLayerChange(m_currentLayer, printer, settings);
        }
        gcode += generateLayer(slices[i], m_currentLayer, m_totalLayers, printer, settings);

        // Progress
        if (m_currentLayer % 10 == 0) {
            emit generationProgress(static_cast<int>((m_currentLayer + 1) * 100 / m_totalLayers),
                                   QString("Generating layer %1/%2").arg(m_currentLayer + 1).arg(m_totalLayers));
        }
    }

    // Shutdown
    gcode += generateShutdown(printer, settings);
    gcode += "\n";

    // Footer
    gcode += generateFooter(printer, settings);

    emit generationComplete(gcode);
    return gcode;
}

void GCodeGenerator::generateAsync(const SliceInfo& sliceInfo, const PrinterProfile& printer, const SliceSettings& settings,
                                   ProgressCallback progress, std::function<void(const QString& gcode)> complete) {
    QtConcurrent::run([this, sliceInfo, &printer, settings, progress, complete]() {
        QString gcode = generateFromLayers(sliceInfo.slices, printer, settings, sliceInfo.boundingBox);
        if (complete) complete(gcode);
    });
}

// ============================================================================
// Header / Footer
// ============================================================================

QString GCodeGenerator::generateHeader(const PrinterProfile& printer, const SliceSettings& settings, const BoundingBox& bounds) {
    QString out;
    writeComment(out, "Generated by ksEditor 3D Printing Module");
    writeComment(out, QString("Printer: %1 (%2)").arg(printer.name).arg(printer.id));
    writeComment(out, QString("Slicing profile: %1").arg(settings.outputFilename.isEmpty() ? "default" : settings.outputFilename));
    writeComment(out, QString("Layers: %1").arg(m_totalLayers));
    writeComment(out, QString("Bounds: X%.1f Y%.1f Z%.1f").arg(bounds.size().x).arg(bounds.size().y).arg(bounds.size().z));
    writeComment(out, QString("Estimated time: %1s").arg(m_totalTime));
    writeComment(out, QString("Estimated filament: %1mm").arg(m_totalFilament));
    writeComment(out, "");

    // Flavor-specific headers
    switch (printer.gcodeFlavor) {
        case GCodeFlavor::Marlin:
        case GCodeFlavor::Prusa:
        case GCodeFlavor::Bambu:
            writeLine(out, "G21 ; Units: millimeters");
            writeLine(out, "G90 ; Absolute positioning");
            writeLine(out, "M82 ; Absolute extrusion");
            break;
        case GCodeFlavor::Klipper:
            writeLine(out, "G21");
            writeLine(out, "G90");
            writeLine(out, "M83 ; Relative extrusion for Klipper");
            m_relativeExtrusion = true;
            break;
        case GCodeFlavor::RepRap:
            writeLine(out, "G21");
            writeLine(out, "G90");
            writeLine(out, "M83");
            m_relativeExtrusion = true;
            break;
        default:
            writeLine(out, "G21");
            writeLine(out, "G90");
            writeLine(out, "M82");
            break;
    }

    return out;
}

QString GCodeGenerator::generateFooter(const PrinterProfile& printer, const SliceSettings& settings) {
    QString out;
    writeComment(out, "");
    writeComment(out, "Print complete");
    writeComment(out, QString("Total filament used: %1mm").arg(m_totalFilament, 0, 'f', 2));
    writeComment(out, QString("Estimated print time: %1s").arg(m_totalTime, 0, 'f', 0));
    return out;
}

// ============================================================================
// Startup / Shutdown
// ============================================================================

QString GCodeGenerator::generateStartup(const PrinterProfile& printer, const SliceSettings& settings) {
    QString out;
    writeComment(out, "=== STARTUP ===");

    QString startup = printer.startGcode.isEmpty() ? defaultStartupGcode(printer, settings) : printer.startGcode;

    // Replace placeholders
    startup.replace("{nozzle_temp}", QString::number(settings.nozzleTemp, 'f', 0));
    startup.replace("{bed_temp}", QString::number(settings.bedTemp, 'f', 0));
    startup.replace("{travel_speed}", QString::number(settings.travelSpeed * 60, 'f', 0)); // mm/min
    startup.replace("{print_speed}", QString::number(settings.printSpeed * 60, 'f', 0));
    startup.replace("{bed_max_y}", QString::number(printer.buildVolumeY, 'f', 1));
    startup.replace("{bed_max_x}", QString::number(printer.buildVolumeX, 'f', 1));

    // Also replace with _ variants
    startup.replace("{nozzle_temperature}", QString::number(settings.nozzleTemp, 'f', 0));
    startup.replace("{bed_temperature}", QString::number(settings.bedTemp, 'f', 0));
    startup.replace("{initial_layer_height}", QString::number(settings.initialLayerHeight > 0 ? settings.initialLayerHeight : settings.layerHeight, 'f', 2));

    out += startup + "\n";

    // Set initial temperatures if not in startup
    if (!startup.contains("M104") && !startup.contains("M109")) {
        out += generateSetHotendTemp(settings.nozzleTemp, true, printer);
    }
    if (!startup.contains("M140") && !startup.contains("M190")) {
        out += generateSetBedTemp(settings.bedTemp, true, printer);
    }

    return out;
}

QString GCodeGenerator::generateShutdown(const PrinterProfile& printer, const SliceSettings& settings) {
    QString out;
    writeComment(out, "=== SHUTDOWN ===");

    QString shutdown = printer.endGcode.isEmpty() ? defaultShutdownGcode(printer, settings) : printer.endGcode;

    shutdown.replace("{bed_max_y}", QString::number(printer.buildVolumeY, 'f', 1));
    shutdown.replace("{bed_max_x}", QString::number(printer.buildVolumeX, 'f', 1));

    out += shutdown + "\n";
    return out;
}

QString GCodeGenerator::defaultStartupGcode(const PrinterProfile& printer, const SliceSettings& settings) {
    return QString(R"(
; Default startup
G21
G90
M82
M104 S%1
M140 S%2
G28
G1 Z5 F5000
M190 S%2
M109 S%1
G92 E0
G1 X10 Y10 Z0.2 F3000
G1 X100 E15 F1000
G92 E0
)").arg(settings.nozzleTemp).arg(settings.bedTemp);
}

QString GCodeGenerator::defaultShutdownGcode(const PrinterProfile& printer, const SliceSettings& settings) {
    return QString(R"(
; Default shutdown
M104 S0
M140 S0
G91
G1 E-2 F2700
G1 Z5 F1000
G90
G1 X0 Y%1 F5000
M84
)").arg(printer.buildVolumeY);
}

// ============================================================================
// Layer Generation
// ============================================================================

QString GCodeGenerator::generateLayer(const LayerSlice& layer, int layerIndex, int totalLayers,
                                      const PrinterProfile& printer, const SliceSettings& settings) {
    QString out;

    if (layer.isFirstLayer) {
        writeComment(out, QString("=== LAYER %1 (FIRST LAYER) ===").arg(layerIndex + 1));
        // First layer specific settings
        setFeedrate(out, settings.initialLayerSpeed * 60);
    } else if (layer.isLastLayer) {
        writeComment(out, QString("=== LAYER %1 (LAST LAYER) ===").arg(layerIndex + 1));
    } else {
        writeComment(out, QString("=== LAYER %1 ===").arg(layerIndex + 1));
    }

    writeComment(out, QString("Z = %1").arg(Impl::fmt(layer.z, 3)));

    // Set layer Z
    moveTo(out, m_currentX, m_currentY, layer.z, settings.travelSpeed * 60);

    // Fan control
    if (settings.enableCooling) {
        int fanSpeed = layerIndex < settings.fanStartLayer ? settings.initialFanSpeed : settings.fanSpeed;
        out += generateFanSpeed(fanSpeed, settings);
    }

    // Process perimeters first (outer wall, then inner walls)
    if (!layer.perimeters.empty()) {
        writeComment(out, "--- Perimeters ---");
        out += generatePerimeters(layer.perimeters, settings, true); // outer wall first

        // Inner walls
        if (settings.wallCount > 1) {
            setFeedrate(out, settings.innerWallSpeed * 60);
            out += generatePerimeters(layer.perimeters, settings, false);
        }
    }

    // Infill
    if (!layer.infill.empty()) {
        writeComment(out, "--- Infill ---");
        setFeedrate(out, settings.infillSpeed * 60);
        out += generateInfill(layer.infill, settings);
    }

    // Support
    if (!layer.support.empty()) {
        writeComment(out, "--- Support ---");
        setFeedrate(out, settings.supportSpeed * 60);
        out += generateSupport(layer.support, settings);
    }

    // Brim/Skirt (first layer only)
    if (layer.isFirstLayer) {
        if (!layer.brim.empty()) {
            writeComment(out, "--- Brim/Skirt ---");
            setFeedrate(out, settings.initialLayerSpeed * 60);
            out += generateBrim(layer.brim, settings);
        }
    }

    return out;
}

QString GCodeGenerator::generateLayerChange(int layerIndex, const PrinterProfile& printer, const SliceSettings& settings) {
    QString out;
    if (!printer.layerChangeGcode.isEmpty()) {
        QString lc = printer.layerChangeGcode;
        lc.replace("{layer_num}", QString::number(layerIndex + 1));
        lc.replace("{layer_z}", Impl::fmt(settings.layerHeight * (layerIndex + 1), 3));
        out += lc + "\n";
    }
    return out;
}

// ============================================================================
// Feature Generation
// ============================================================================

QString GCodeGenerator::generatePerimeters(const Polygons2D& perimeters, const SliceSettings& settings, bool outerWall) {
    QString out;

    double speed = outerWall ? settings.outerWallSpeed : settings.innerWallSpeed;
    setFeedrate(out, speed * 60);

    for (const auto& poly : perimeters) {
        if (poly.vertices.size() < 3) continue;

        // Move to start
        const auto& start = poly.vertices.front();
        travelTo(out, start.x, start.y, m_currentZ);

        // Prime if needed
        if (settings.retractionEnabled && m_currentE > 0) {
            out += generatePrime(settings);
        }

        // Trace perimeter
        for (size_t i = 0; i < poly.vertices.size(); ++i) {
            const auto& v = poly.vertices[i];
            double extrusion = calculateExtrusion(
                (i > 0) ? std::sqrt(std::pow(v.x - poly.vertices[i-1].x, 2) + std::pow(v.y - poly.vertices[i-1].y, 2)) : 0,
                settings.lineWidth, settings.layerHeight, settings.filamentDiameter
            );
            moveTo(out, v.x, v.y, m_currentZ, speed * 60, extrusion);
        }

        // Close loop
        const auto& end = poly.vertices.front();
        double extrusion = std::sqrt(std::pow(end.x - poly.vertices.back().x, 2) + std::pow(end.y - poly.vertices.back().y, 2));
        extrusion = calculateExtrusion(extrusion, settings.lineWidth, settings.layerHeight, settings.filamentDiameter);
        moveTo(out, end.x, end.y, m_currentZ, speed * 60, extrusion);
    }

    return out;
}

QString GCodeGenerator::generateInfill(const Polygons2D& infill, const SliceSettings& settings) {
    QString out;
    setFeedrate(out, settings.infillSpeed * 60);

    for (const auto& poly : infill) {
        if (poly.vertices.size() < 2) continue;

        // Infill is typically lines, not closed loops
        travelTo(out, poly.vertices[0].x, poly.vertices[0].y, m_currentZ);

        for (size_t i = 1; i < poly.vertices.size(); ++i) {
            const auto& v = poly.vertices[i];
            const auto& prev = poly.vertices[i-1];
            double dist = std::sqrt(std::pow(v.x - prev.x, 2) + std::pow(v.y - prev.y, 2));
            double extrusion = calculateExtrusion(dist, settings.infillLineWidth > 0 ? settings.infillLineWidth : settings.lineWidth,
                                                  settings.layerHeight, settings.filamentDiameter);
            moveTo(out, v.x, v.y, m_currentZ, settings.infillSpeed * 60, extrusion);
        }
    }

    return out;
}

QString GCodeGenerator::generateSupport(const Polygons2D& support, const SliceSettings& settings) {
    QString out;
    setFeedrate(out, settings.supportSpeed * 60);

    for (const auto& poly : support) {
        if (poly.vertices.size() < 2) continue;

        travelTo(out, poly.vertices[0].x, poly.vertices[0].y, m_currentZ);

        for (size_t i = 1; i < poly.vertices.size(); ++i) {
            const auto& v = poly.vertices[i];
            const auto& prev = poly.vertices[i-1];
            double dist = std::sqrt(std::pow(v.x - prev.x, 2) + std::pow(v.y - prev.y, 2));
            double extrusion = calculateExtrusion(dist, settings.lineWidth, settings.layerHeight, settings.filamentDiameter);
            moveTo(out, v.x, v.y, m_currentZ, settings.supportSpeed * 60, extrusion);
        }
    }

    return out;
}

QString GCodeGenerator::generateBrim(const Polygons2D& brim, const SliceSettings& settings) {
    QString out;
    setFeedrate(out, settings.initialLayerSpeed * 60);

    for (const auto& poly : brim) {
        if (poly.vertices.size() < 3) continue;

        travelTo(out, poly.vertices[0].x, poly.vertices[0].y, m_currentZ);

        for (size_t i = 1; i < poly.vertices.size(); ++i) {
            const auto& v = poly.vertices[i];
            const auto& prev = poly.vertices[i-1];
            double dist = std::sqrt(std::pow(v.x - prev.x, 2) + std::pow(v.y - prev.y, 2));
            double extrusion = calculateExtrusion(dist, settings.lineWidth, settings.initialLayerHeight > 0 ? settings.initialLayerHeight : settings.layerHeight,
                                                  settings.filamentDiameter);
            moveTo(out, v.x, v.y, m_currentZ, settings.initialLayerSpeed * 60, extrusion);
        }
        // Close
        const auto& start = poly.vertices.front();
        const auto& end = poly.vertices.back();
        double dist = std::sqrt(std::pow(start.x - end.x, 2) + std::pow(start.y - end.y, 2));
        double extrusion = calculateExtrusion(dist, settings.lineWidth, settings.initialLayerHeight > 0 ? settings.initialLayerHeight : settings.layerHeight,
                                              settings.filamentDiameter);
        moveTo(out, start.x, start.y, m_currentZ, settings.initialLayerSpeed * 60, extrusion);
    }

    return out;
}

QString GCodeGenerator::generateSkirt(const Polygons2D& skirt, const SliceSettings& settings) {
    return generateBrim(skirt, settings); // Similar generation
}

// ============================================================================
// Movement & Extrusion
// ============================================================================

QString GCodeGenerator::generateTravel(const Vector3& from, const Vector3& to, const SliceSettings& settings) {
    QString out;

    // Retract before travel if enabled and distance > min
    double dist = std::sqrt(std::pow(to.x - from.x, 2) + std::pow(to.y - from.y, 2));
    if (settings.retractionEnabled && dist > settings.minTravelForRetract) {
        out += generateRetract(settings);
    }

    // Z-hop if enabled
    if (settings.zHopEnabled && settings.zHopHeight > 0) {
        double hopZ = from.z + settings.zHopHeight;
        setFeedrate(out, settings.zHopSpeed > 0 ? settings.zHopSpeed * 60 : settings.travelSpeed * 60);
        moveTo(out, from.x, from.y, hopZ, settings.travelSpeed * 60, 0);
    }

    // Travel move
    setFeedrate(out, settings.travelSpeed * 60);
    moveTo(out, to.x, to.y, to.z, settings.travelSpeed * 60, 0);

    // Z-hop down
    if (settings.zHopEnabled && settings.zHopHeight > 0) {
        setFeedrate(out, settings.zHopSpeed > 0 ? settings.zHopSpeed * 60 : settings.travelSpeed * 60);
        moveTo(out, to.x, to.y, to.z, settings.travelSpeed * 60, 0);
    }

    // Prime after travel
    if (settings.retractionEnabled && dist > settings.minTravelForRetract) {
        out += generatePrime(settings);
    }

    return out;
}

QString GCodeGenerator::generateRetract(const SliceSettings& settings) {
    QString out;
    if (settings.retractDistance > 0) {
        double e = m_relativeExtrusion ? -settings.retractDistance : m_currentE - settings.retractDistance;
        writeLine(out, QString("G1 E%1 F%2 ; Retract").arg(Impl::fmtE(e)).arg(settings.retractSpeed * 60));
        if (m_relativeExtrusion) {
            m_currentE -= settings.retractDistance;
        } else {
            m_currentE = e;
        }
    }
    return out;
}

QString GCodeGenerator::generatePrime(const SliceSettings& settings) {
    QString out;
    double primeDist = settings.primeDistance > 0 ? settings.primeDistance : settings.retractDistance;
    double e = m_relativeExtrusion ? primeDist : m_currentE + primeDist;
    writeLine(out, QString("G1 E%1 F%2 ; Prime").arg(Impl::fmtE(e)).arg(settings.retractSpeed * 60));
    if (m_relativeExtrusion) {
        m_currentE += primeDist;
    } else {
        m_currentE = e;
    }
    return out;
}

QString GCodeGenerator::generateZHop(double z, const SliceSettings& settings) {
    QString out;
    setFeedrate(out, settings.zHopSpeed > 0 ? settings.zHopSpeed * 60 : settings.travelSpeed * 60);
    moveTo(out, m_currentX, m_currentY, z, settings.zHopSpeed > 0 ? settings.zHopSpeed * 60 : settings.travelSpeed * 60, 0);
    return out;
}

// ============================================================================
// Temperature & Fan
// ============================================================================

QString GCodeGenerator::generateSetHotendTemp(double temp, bool wait, const PrinterProfile& printer) {
    QString out;
    if (wait) {
        writeLine(out, QString("M109 S%1 ; Wait for hotend").arg(static_cast<int>(temp)));
    } else {
        writeLine(out, QString("M104 S%1 ; Set hotend temp").arg(static_cast<int>(temp)));
    }
    return out;
}

QString GCodeGenerator::generateSetBedTemp(double temp, bool wait, const PrinterProfile& printer) {
    QString out;
    if (wait) {
        writeLine(out, QString("M190 S%1 ; Wait for bed").arg(static_cast<int>(temp)));
    } else {
        writeLine(out, QString("M140 S%1 ; Set bed temp").arg(static_cast<int>(temp)));
    }
    return out;
}

QString GCodeGenerator::generateFanSpeed(int speed, const SliceSettings& settings) {
    QString out;
    speed = std::clamp(speed, 0, 255);
    writeLine(out, QString("M106 S%1 ; Fan speed %2%").arg(speed).arg(speed * 100 / 255));
    return out;
}

// ============================================================================
// Helper Functions
// ============================================================================

void GCodeGenerator::resetState() {
    m_currentX = m_currentY = m_currentZ = 0;
    m_currentE = 0;
    m_currentFeedrate = 0;
    m_relativeExtrusion = false;
    m_relativePositioning = false;
    m_currentLayer = 0;
    m_totalLayers = 0;
    m_totalFilament = 0;
    m_totalTime = 0;
}

void GCodeGenerator::writeLine(QString& output, const QString& line) {
    output += line + "\n";
}

void GCodeGenerator::writeComment(QString& output, const QString& comment) {
    if (comment.isEmpty()) {
        output += "\n";
    } else {
        output += "; " + comment + "\n";
    }
}

void GCodeGenerator::moveTo(QString& output, double x, double y, double z, double feedrate, double extrusion) {
    QString line = "G1";
    if (std::abs(x - m_currentX) > 0.001) line += " X" + Impl::fmt(x);
    if (std::abs(y - m_currentY) > 0.001) line += " Y" + Impl::fmt(y);
    if (std::abs(z - m_currentZ) > 0.001) line += " Z" + Impl::fmt(z);
    if (extrusion != 0) line += " E" + Impl::fmtE(extrusion);
    if (feedrate > 0 && std::abs(feedrate - m_currentFeedrate) > 1) {
        line += " F" + Impl::fmt(feedrate, 0);
        m_currentFeedrate = feedrate;
    }
    writeLine(output, line);

    m_currentX = x;
    m_currentY = y;
    m_currentZ = z;
    if (extrusion != 0) {
        if (m_relativeExtrusion) {
            m_currentE += extrusion;
        } else {
            m_currentE = extrusion;
        }
        m_totalFilament += std::abs(extrusion);
    }
}

void GCodeGenerator::travelTo(QString& output, double x, double y, double z) {
    moveTo(output, x, y, z, m_currentFeedrate > 0 ? m_currentFeedrate : 9000, 0);
}

void GCodeGenerator::setFeedrate(QString& output, double feedrate) {
    if (std::abs(feedrate - m_currentFeedrate) > 1) {
        writeLine(output, QString("G1 F%1").arg(Impl::fmt(feedrate, 0)));
        m_currentFeedrate = feedrate;
    }
}

void GCodeGenerator::setExtrusionMode(QString& output, bool relative) {
    if (relative != m_relativeExtrusion) {
        writeLine(output, relative ? "M83 ; Relative extrusion" : "M82 ; Absolute extrusion");
        m_relativeExtrusion = relative;
    }
}

void GCodeGenerator::setPositioningMode(QString& output, bool relative) {
    if (relative != m_relativePositioning) {
        writeLine(output, relative ? "G91 ; Relative positioning" : "G90 ; Absolute positioning");
        m_relativePositioning = relative;
    }
}

void GCodeGenerator::setFanSpeed(QString& output, int speed) {
    writeLine(output, QString("M106 S%1").arg(std::clamp(speed, 0, 255)));
}

QString GCodeGenerator::formatCoordinate(double value, int precision) const {
    return QString::number(value, 'f', precision);
}

QString GCodeGenerator::formatExtrusion(double value, int precision) const {
    return QString::number(value, 'f', precision);
}

double GCodeGenerator::calculateExtrusion(double distance, double lineWidth, double layerHeight, double filamentDiameter) const {
    if (distance <= 0) return 0;
    double crossSection = lineWidth * layerHeight;
    double filamentArea = M_PI * filamentDiameter * filamentDiameter / 4.0;
    return distance * crossSection / filamentArea;
}

} // namespace printing
} // namespace ks