# Expand embedded SimulationLoop.cpp from cmake/simloop_{a,b}.b64
set(_ks_sl "${CMAKE_SOURCE_DIR}/src/simulator/SimulationLoop.cpp")
if(EXISTS "${_ks_sl}")
  file(READ "${_ks_sl}" _ks_head LIMIT 400)
  if(_ks_head MATCHES "restore_simloop|#error")
    message(STATUS "ksengine: expanding embedded SimulationLoop.cpp...")
    set(_ks_a "${CMAKE_SOURCE_DIR}/cmake/simloop_a.b64")
    set(_ks_b "${CMAKE_SOURCE_DIR}/cmake/simloop_b.b64")
    if(EXISTS "${_ks_a}" AND EXISTS "${_ks_b}")
      file(READ "${_ks_a}" _ka)
      file(READ "${_ks_b}" _kb)
      set(_ks_b64f "${CMAKE_BINARY_DIR}/_simloop.b64")
      file(WRITE "${_ks_b64f}" "${_ka}${_kb}")
      set(_ks_py "${CMAKE_BINARY_DIR}/_expand_simloop.py")
      file(WRITE "${_ks_py}" "import zlib,base64,sys\nopen(sys.argv[2],'wb').write(zlib.decompress(base64.b64decode(open(sys.argv[1]).read())))\n")
      execute_process(COMMAND python3 "${_ks_py}" "${_ks_b64f}" "${_ks_sl}" RESULT_VARIABLE _ks_rc)
      if(_ks_rc EQUAL 0)
        message(STATUS "ksengine: SimulationLoop.cpp restored from embedded archive")
      else()
        message(WARNING "ksengine: expand failed — run tools/restore_simloop.sh")
      endif()
    else()
      message(WARNING "ksengine: simloop_a/b.b64 missing — run tools/restore_simloop.sh")
    endif()
  endif()
endif()
