# Expand embedded SimulationLoop.cpp
# Prefer plain text parts cmake/simloop_src_*.txt (transparent).
# Fallback: cmake/simloop_z*.b64 (zlib+b64).
set(_ks_sl "${CMAKE_SOURCE_DIR}/src/simulator/SimulationLoop.cpp")
if(EXISTS "${_ks_sl}")
  file(READ "${_ks_sl}" _ks_head LIMIT 400)
  if(_ks_head MATCHES "restore_simloop|#error")
    message(STATUS "ksengine: restoring SimulationLoop.cpp...")
    set(_ks_txt "")
    set(_ks_have_txt FALSE)
    foreach(_i RANGE 0 4)
      set(_f "${CMAKE_SOURCE_DIR}/cmake/simloop_src_${_i}.txt")
      if(EXISTS "${_f}")
        file(READ "${_f}" _chunk)
        string(APPEND _ks_txt "${_chunk}")
        set(_ks_have_txt TRUE)
      endif()
    endforeach()
    if(_ks_have_txt)
      file(WRITE "${_ks_sl}" "${_ks_txt}")
      message(STATUS "ksengine: SimulationLoop.cpp restored from simloop_src_*.txt")
    else()
      set(_ks_b64 "")
      foreach(_i RANGE 0 4)
        set(_f "${CMAKE_SOURCE_DIR}/cmake/simloop_z${_i}.b64")
        if(EXISTS "${_f}")
          file(READ "${_f}" _chunk)
          string(STRIP "${_chunk}" _chunk)
          string(APPEND _ks_b64 "${_chunk}")
        endif()
      endforeach()
      set(_ks_b64f "${CMAKE_BINARY_DIR}/_simloop.b64")
      file(WRITE "${_ks_b64f}" "${_ks_b64}")
      set(_ks_py "${CMAKE_BINARY_DIR}/_expand_simloop.py")
      file(WRITE "${_ks_py}" "import zlib,base64,sys\nopen(sys.argv[2],'wb').write(zlib.decompress(base64.b64decode(open(sys.argv[1]).read())))\n")
      execute_process(COMMAND python3 "${_ks_py}" "${_ks_b64f}" "${_ks_sl}" RESULT_VARIABLE _ks_rc)
      if(_ks_rc EQUAL 0)
        message(STATUS "ksengine: SimulationLoop.cpp restored from simloop_z*.b64")
      else()
        message(WARNING "ksengine: expand failed — run tools/restore_simloop.sh")
      endif()
    endif()
  endif()
endif()
