#include "SetupEditorQmlBridge.h"
#include "CarSetupEditor.h"
#include "sdk/kseditor/engine/sys/LogManager.h"
#include <QGroupBox>
#include <QFormLayout>
#include <cmath>
#include <algorithm>
#include <QFile>
#include <QFileInfo>
#include <QDir>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QTextStream>
#include <QStandardPaths>
#include <QDebug>
#include <QtMath>

namespace ks {

SetupEditorQmlBridge* SetupEditorQmlBridge::s_instance = nullptr;

SetupEditorQmlBridge* SetupEditorQmlBridge::instance() {
    if (!s_instance) {
        s_instance = new SetupEditorQmlBridge();
    }
    return s_instance;
}

SetupEditorQmlBridge::SetupEditorQmlBridge(QObject* parent)
    : QObject(parent)
{
    m_setupDir = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation) + "/Assetto Corsa/setups";
}

void SetupEditorQmlBridge::loadSetup(const QString& path) {
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        emit errorMessage("Cannot open setup: " + path);
        return;
    }

    m_currentSetupPath = path;
    m_currentSetup.clear();
    m_isModified = false;

    QTextStream in(&file);
    QString currentSection;
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(";")) continue;

        if (line.startsWith("[") && line.endsWith("]")) {
            currentSection = line.mid(1, line.length() - 2);
            continue;
        }

        int eqIdx = line.indexOf("=");
        if (eqIdx > 0) {
            QString key = line.left(eqIdx).trimmed();
            QString value = line.mid(eqIdx + 1).trimmed();
            m_currentSetup[currentSection + "." + key] = value;
        }
    }

    file.close();
    emit statusMessage("Loaded setup: " + QFileInfo(path).fileName());
    emit setupLoaded();
}

void SetupEditorQmlBridge::saveSetup(const QString& path) {
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        emit errorMessage("Cannot save setup: " + path);
        return;
    }

    QTextStream out(&file);
    out << "; ksEditor Setup Export\n";
    out << "; Generated by ksEditor\n\n";

    QString currentSection;
    for (auto it = m_currentSetup.constBegin(); it != m_currentSetup.constEnd(); ++it) {
        QString key = it.key();
        QString value = it.value().toString();

        if (key.contains(".")) {
            QString section = key.section(".", 0, 0);
            QString subKey = key.section(".", 1);
            if (section != currentSection) {
                if (!currentSection.isEmpty()) out << "\n";
                out << "[" << section << "]\n";
                currentSection = section;
            }
            out << subKey << "=" << value << "\n";
        } else {
            out << key << "=" << value << "\n";
        }
    }

    file.close();
    m_currentSetupPath = path;
    m_isModified = false;
    emit statusMessage("Saved setup: " + QFileInfo(path).fileName());
    emit setupApplied();
}

void SetupEditorQmlBridge::analyzeSetup() {
    if (m_currentSetup.isEmpty()) {
        emit errorMessage("No setup loaded for analysis");
        return;
    }

    // Analyze key parameters and provide recommendations
    QStringList recommendations;

    if (m_currentSetup.contains("BASIC.WEIGHT")) {
        float weight = m_currentSetup["BASIC.WEIGHT"].toFloat();
        if (weight > 1500) recommendations.append("Car is heavy - consider softer springs");
        if (weight < 800) recommendations.append("Car is light - consider stiffer springs");
    }

    if (m_currentSetup.contains("FRONT.SPRING_RATE") && m_currentSetup.contains("REAR.SPRING_RATE")) {
        float front = m_currentSetup["FRONT.SPRING_RATE"].toFloat();
        float rear = m_currentSetup["REAR.SPRING_RATE"].toFloat();
        if (front > rear * 1.3f)
            recommendations.append("Front springs much stiffer than rear - may cause oversteer");
        if (rear > front * 1.3f)
            recommendations.append("Rear springs much stiffer than front - may cause understeer");
    }

    if (m_currentSetup.contains("FRONT.CAMBER") && m_currentSetup.contains("REAR.CAMBER")) {
        float frontCamber = m_currentSetup["FRONT.CAMBER"].toFloat();
        float rearCamber = m_currentSetup["REAR.CAMBER"].toFloat();
        if (std::abs(frontCamber) > 3.5f)
            recommendations.append("Front camber exceeds 3.5 degrees - excessive tire wear expected");
        if (std::abs(rearCamber) > 3.0f)
            recommendations.append("Rear camber exceeds 3.0 degrees - excessive tire wear expected");
    }

    if (m_currentSetup.contains("BASIC.FINAL_RATIO")) {
        float finalRatio = m_currentSetup["BASIC.FINAL_RATIO"].toFloat();
        if (finalRatio > 5.0f) recommendations.append("Very short final ratio - high acceleration, low top speed");
        if (finalRatio < 2.5f) recommendations.append("Very long final ratio - high top speed, low acceleration");
    }

    emit setupAnalysisComplete(recommendations);
    emit statusMessage(QString("Setup analysis complete: %1 recommendations").arg(recommendations.size()));
}

void SetupEditorQmlBridge::compareWith(const QString& otherPath) {
    QVariantMap otherSetup;
    QFile file(otherPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        emit errorMessage("Cannot open setup for comparison: " + otherPath);
        return;
    }

    QTextStream in(&file);
    QString currentSection;
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(";")) continue;
        if (line.startsWith("[") && line.endsWith("]")) {
            currentSection = line.mid(1, line.length() - 2);
            continue;
        }
        int eqIdx = line.indexOf("=");
        if (eqIdx > 0) {
            otherSetup[currentSection + "." + line.left(eqIdx).trimmed()] = line.mid(eqIdx + 1).trimmed();
        }
    }
    file.close();

    // Find differences
    QStringList diffs;
    QSet<QString> allKeys;
    for (auto it = m_currentSetup.begin(); it != m_currentSetup.end(); ++it) allKeys.insert(it.key());
    for (auto it = otherSetup.begin(); it != otherSetup.end(); ++it) allKeys.insert(it.key());

    for (const QString& key : allKeys) {
        QString currentVal = m_currentSetup.value(key).toString();
        QString otherVal = otherSetup.value(key).toString();
        if (currentVal != otherVal) {
            diffs.append(QString("%1: %2 -> %3").arg(key).arg(otherVal, currentVal));
        }
    }

    emit comparisonComplete(diffs);
    if (diffs.isEmpty()) {
        emit statusMessage("Setups are identical");
    } else {
        emit statusMessage(QString("Found %1 differences between setups").arg(diffs.size()));
    }
}

// ── Telemetry-driven setup ──────────────────────────────────────────────

QVariantMap SetupEditorQmlBridge::importTelemetryLap(const QVariantMap& lapData) {
    TelemetryLapForSetup lap;
    lap.lapNumber = lapData.value("lapNumber").toInt();
    lap.lapTime = lapData.value("lapTime").toDouble();
    lap.sector1 = lapData.value("sector1").toDouble();
    lap.sector2 = lapData.value("sector2").toDouble();
    lap.sector3 = lapData.value("sector3").toDouble();
    lap.topSpeed = static_cast<float>(lapData.value("topSpeed").toDouble());
    lap.avgSpeed = static_cast<float>(lapData.value("avgSpeed").toDouble());
    lap.maxGForce = static_cast<float>(lapData.value("maxGForce").toDouble());

    // Import samples if present
    QVariantList samples = lapData.value("samples").toList();
    int throttleOn = 0, brakeOn = 0, coast = 0;
    int total = samples.size();

    for (const auto& s : samples) {
        QVariantMap sm = s.toMap();
        TelemetryDrivingSample sample;
        sample.speed = static_cast<float>(sm.value("speed").toDouble());
        sample.throttle = static_cast<float>(sm.value("throttle").toDouble());
        sample.brake = static_cast<float>(sm.value("brake").toDouble());
        sample.steering = static_cast<float>(sm.value("steering").toDouble());
        sample.lateralG = static_cast<float>(sm.value("latG").toDouble());
        sample.longitudinalG = static_cast<float>(sm.value("lonG").toDouble());
        lap.samples.append(sample);

        if (sample.throttle > 0.05f) throttleOn++;
        else if (sample.brake > 0.05f) brakeOn++;
        else coast++;
    }

    if (total > 0) {
        lap.throttleTimePercent = 100.0f * throttleOn / total;
        lap.brakeTimePercent = 100.0f * brakeOn / total;
        lap.coastTimePercent = 100.0f * coast / total;
    }

    m_importedLaps.append(lap);
    emit telemetryOptimizationReady(QVariantMap{{"imported", lap.lapNumber}, {"lapTime", lap.lapTime}});
    return {{"lapNumber", lap.lapNumber}, {"throttlePercent", lap.throttleTimePercent},
            {"brakePercent", lap.brakeTimePercent}, {"coastPercent", lap.coastTimePercent}};
}

QVariantList SetupEditorQmlBridge::analyzeDrivingStyle() {
    QVariantList insights;

    if (m_importedLaps.isEmpty()) {
        emit errorMessage("No telemetry laps imported");
        return insights;
    }

    // Find the best lap
    const TelemetryLapForSetup* bestLap = nullptr;
    for (const auto& lap : m_importedLaps) {
        if (!bestLap || lap.lapTime < bestLap->lapTime) bestLap = &lap;
    }
    if (!bestLap) return insights;

    // Analyze driving style from best lap
    float avgSteering = 0;
    int steeringSamples = 0;
    float maxSteeringSpeed = 0;
    float lateBrakingScore = 0;
    int brakeEvents = 0;

    for (size_t i = 1; i < bestLap->samples.size(); ++i) {
        const auto& prev = bestLap->samples[i - 1];
        const auto& cur = bestLap->samples[i];

        avgSteering += std::abs(cur.steering);
        steeringSamples++;

        // Detect steering at high speed
        if (cur.speed > 100 && std::abs(cur.steering) > 0.3f) {
            maxSteeringSpeed = std::max(maxSteeringSpeed, cur.speed);
        }

        // Detect late braking
        if (cur.brake > 0.3f && prev.brake < 0.1f) {
            brakeEvents++;
        }
    }

    if (steeringSamples > 0) avgSteering /= steeringSamples;

    // Generate insights
    QVariantMap style;
    if (avgSteering > 0.25f) {
        style["type"] = "aggressive_steering";
        style["message"] = "Aggressive steering input detected";
        style["suggestion"] = "Increase front ARB stiffness or reduce front camber";
        insights.append(style);
    }

    if (bestLap->throttleTimePercent > 70) {
        QVariantMap t;
        t["type"] = "early_throttle";
        t["message"] = QString("Heavy on throttle (%1% of lap)").arg(bestLap->throttleTimePercent, 0, 'f', 1);
        t["suggestion"] = "Consider softer rear springs for better traction on exit";
        insights.append(t);
    }

    if (bestLap->brakeTimePercent > 25) {
        QVariantMap b;
        b["type"] = "heavy_braking";
        b["message"] = QString("Brake-heavy driving style (%1% of lap)").arg(bestLap->brakeTimePercent, 0, 'f', 1);
        b["suggestion"] = "Increase brake torque or move bias rearward for better rotation";
        insights.append(b);
    }

    if (maxSteeringSpeed > 150) {
        QVariantMap s;
        s["type"] = "high_speed_correction";
        s["message"] = QString("Steering corrections at %1 km/h").arg(maxSteeringSpeed, 0, 'f', 0);
        s["suggestion"] = "Increase rear wing angle or reduce rear ride height";
        insights.append(s);
    }

    if (bestLap->maxGForce > 1.5f) {
        QVariantMap g;
        g["type"] = "high_grip";
        g["message"] = QString("High lateral load (%1 G)").arg(bestLap->maxGForce, 0, 'f', 2);
        g["suggestion"] = "Stiffen anti-roll bars and increase tire pressure";
        insights.append(g);
    }

    emit drivingAnalysisComplete(insights);
    return insights;
}

QVariantMap SetupEditorQmlBridge::autoOptimizeSetup() {
    if (m_importedLaps.isEmpty()) {
        emit errorMessage("No telemetry data for optimization");
        return {};
    }

    const TelemetryLapForSetup* bestLap = nullptr;
    for (const auto& lap : m_importedLaps) {
        if (!bestLap || lap.lapTime < bestLap->lapTime) bestLap = &lap;
    }
    if (!bestLap) return {};

    QVariantMap changes;
    QStringList recommendations;

    // Optimize based on driving style and telemetry
    float avgThrottle = 0, avgBrake = 0, avgSteering = 0;
    int count = bestLap->samples.size();
    for (const auto& s : bestLap->samples) {
        avgThrottle += s.throttle;
        avgBrake += s.brake;
        avgSteering += std::abs(s.steering);
    }
    if (count > 0) {
        avgThrottle /= count;
        avgBrake /= count;
        avgSteering /= count;
    }

    // Adjust differential based on throttle behavior
    if (avgThrottle > 0.3f) {
        QString currentDiff = m_currentSetup.value("DIFFERENTIAL.DRIVE_POWER", "0.5").toString();
        float diffVal = currentDiff.toFloat();
        if (avgSteering > 0.2f) {
            changes["DIFFERENTIAL.DRIVE_POWER"] = QString::number(std::min(diffVal + 0.1f, 1.0f), 'f', 4);
            recommendations.append("Increased power diff lock for better traction under throttle");
        } else {
            changes["DIFFERENTIAL.DRIVE_POWER"] = QString::number(std::max(diffVal - 0.1f, 0.2f), 'f', 4);
            recommendations.append("Reduced power diff lock for better corner entry");
        }
    }

    // Adjust brake bias based on braking behavior
    if (bestLap->brakeTimePercent > 20) {
        QString currentBias = m_currentSetup.value("BRAKES.FRONT_BIAS", "56").toString();
        float bias = currentBias.toFloat();
        if (avgBrake > 0.4f) {
            changes["BRAKES.FRONT_BIAS"] = QString::number(std::min(bias + 2.0f, 65.0f), 'f', 2);
            recommendations.append("Moved brake bias forward for more stable braking");
        }
    }

    // Adjust tire pressure based on lateral loads
    if (bestLap->maxGForce > 1.4f) {
        QString currentFront = m_currentSetup.value("TYRES.FRONT_PRESSURE_L", "26").toString();
        QString currentRear = m_currentSetup.value("TYRES.REAR_PRESSURE_L", "24").toString();
        changes["TYRES.FRONT_PRESSURE_L"] = QString::number(std::min(currentFront.toFloat() + 1.0f, 35.0f), 'f', 2);
        changes["TYRES.FRONT_PRESSURE_R"] = changes["TYRES.FRONT_PRESSURE_L"];
        changes["TYRES.REAR_PRESSURE_L"] = QString::number(std::min(currentRear.toFloat() + 1.0f, 35.0f), 'f', 2);
        changes["TYRES.REAR_PRESSURE_R"] = changes["TYRES.REAR_PRESSURE_L"];
        recommendations.append("Increased tire pressure for high lateral loads");
    }

    // Adjust final ratio based on top speed usage
    if (bestLap->topSpeed > 250) {
        QString currentRatio = m_currentSetup.value("BASIC.FINAL_RATIO", "3.50").toString();
        float ratio = currentRatio.toFloat();
        changes["BASIC.FINAL_RATIO"] = QString::number(std::max(ratio - 0.2, 2.5), 'f', 2);
        recommendations.append("Lengthened final ratio for higher top speed");
    } else if (bestLap->topSpeed < 180) {
        QString currentRatio = m_currentSetup.value("BASIC.FINAL_RATIO", "3.50").toString();
        float ratio = currentRatio.toFloat();
        changes["BASIC.FINAL_RATIO"] = QString::number(std::min(ratio + 0.3, 6.0), 'f', 2);
        recommendations.append("Shortened final ratio for better acceleration");
    }

    QVariantMap result;
    result["changes"] = changes;
    result["recommendations"] = QVariant::fromValue(recommendations);
    result["basedOnLap"] = bestLap->lapNumber;

    emit telemetryOptimizationReady(result);
    emit statusMessage(QString("Setup optimized based on lap %1 (%2 changes)")
                       .arg(bestLap->lapNumber).arg(changes.size()));

    // Apply the changes
    for (auto it = changes.begin(); it != changes.end(); ++it) {
        m_currentSetup[it.key()] = it.value();
    }
    m_isModified = true;

    return result;
}

QVariantMap SetupEditorQmlBridge::getTelemetryAnalysis() const {
    QVariantMap summary;
    summary["importedLaps"] = m_importedLaps.size();
    if (!m_importedLaps.isEmpty()) {
        const auto* bestLap = &m_importedLaps[0];
        for (const auto& lap : m_importedLaps) {
            if (lap.lapTime > 0 && lap.lapTime < bestLap->lapTime) {
                bestLap = &lap;
            }
        }
        summary["bestLapTime"] = bestLap->lapTime;
        summary["bestLapNumber"] = bestLap->lapNumber;
        summary["avgThrottlePercent"] = bestLap->throttleTimePercent;
        summary["avgBrakePercent"] = bestLap->brakeTimePercent;
        summary["avgCoastPercent"] = bestLap->coastTimePercent;
        summary["maxGForce"] = bestLap->maxGForce;
        summary["topSpeed"] = bestLap->topSpeed;
    }
    return summary;
}

void SetupEditorQmlBridge::resetToDefault() {
    m_currentSetup.clear();
    m_currentSetup["BASIC.WEIGHT"] = "1200";
    m_currentSetup["BASIC.FINAL_RATIO"] = "3.50";
    m_currentSetup["BASIC.MAX_RPM"] = "7500";
    m_currentSetup["FRONT.SPRING_RATE"] = "80000";
    m_currentSetup["FRONT.DAMPING"] = "5000";
    m_currentSetup["FRONT.ARB"] = "20";
    m_currentSetup["REAR.SPRING_RATE"] = "70000";
    m_currentSetup["REAR.DAMPING"] = "4500";
    m_currentSetup["REAR.ARB"] = "15";
    m_currentSetup["FRONT.CAMBER"] = "-2.5";
    m_currentSetup["REAR.CAMBER"] = "-1.5";
    m_currentSetup["FRONT.TOE"] = "0.1";
    m_currentSetup["REAR.TOE"] = "0.2";
    m_currentSetup["FRONT.CASTER"] = "6.0";
    m_currentSetup["BRAKES.TORQUE"] = "2000";
    m_currentSetup["BRAKES.BIAS"] = "0.60";
    m_currentSetup["AERO.CD"] = "0.35";
    m_currentSetup["AERO.FRONT_AREA"] = "2.0";
    m_currentSetup["TIRE.PRESSURE_FRONT"] = "26";
    m_currentSetup["TIRE.PRESSURE_REAR"] = "27";
    m_currentSetup["DIFFERENTIAL.POWER"] = "60";
    m_currentSetup["DIFFERENTIAL.COAST"] = "30";
    m_frontBump = 50;
    m_rearBump = 50;
    m_frontRebound = 50;
    m_rearRebound = 50;
    m_frontSpring = 50;
    m_rearSpring = 50;
    m_rideHeight = 50;
    m_frontWing = 50;
    m_rearWing = 50;
    m_preload = 50;
    m_brakeBias = 50;
    m_brakePower = 50;
    m_isModified = true;
    emit statusMessage("Reset to default setup");
    emit setupLoaded();
}

void SetupEditorQmlBridge::applyPreset(const QString& name) {
    CarSetupEditor::CarSetup preset;
    if (name.compare("Qualifying", Qt::CaseInsensitive) == 0)
        preset = CarSetupEditor::getQualifyingSetup();
    else if (name.compare("Race", Qt::CaseInsensitive) == 0)
        preset = CarSetupEditor::getRaceSetup();
    else if (name.compare("Wet", Qt::CaseInsensitive) == 0)
        preset = CarSetupEditor::getWetSetup();
    else if (name.compare("Drift", Qt::CaseInsensitive) == 0)
        preset = CarSetupEditor::getDriftSetup();
    else if (name.compare("Endurance", Qt::CaseInsensitive) == 0)
        preset = CarSetupEditor::getEnduranceSetup();
    else {
        emit statusMessage("Unknown preset: " + name);
        return;
    }

    m_currentSetup.clear();
    m_currentSetup["BASIC.WEIGHT"] = QString::number(preset.engine.fuelCapacity + 1200);
    m_currentSetup["FRONT.SPRING_RATE"] = QString::number(preset.suspension.frontSpringRate[0]);
    m_currentSetup["REAR.SPRING_RATE"] = QString::number(preset.suspension.rearSpringRate[0]);
    m_currentSetup["FRONT.DAMPING"] = QString::number(preset.suspension.frontBumpDamper[0]);
    m_currentSetup["REAR.DAMPING"] = QString::number(preset.suspension.rearBumpDamper[0]);
    m_currentSetup["FRONT.ARB"] = QString::number(preset.suspension.frontARB);
    m_currentSetup["REAR.ARB"] = QString::number(preset.suspension.rearARB);
    m_currentSetup["FRONT.CAMBER"] = QString::number(preset.tyres.frontCamber[0]);
    m_currentSetup["REAR.CAMBER"] = QString::number(preset.tyres.rearCamber[0]);
    m_currentSetup["FRONT.TOE"] = QString::number(preset.tyres.frontToe[0]);
    m_currentSetup["REAR.TOE"] = QString::number(preset.tyres.rearToe[0]);
    m_currentSetup["BRAKES.TORQUE"] = QString::number(preset.brakes.brakePressure);
    m_currentSetup["BRAKES.BIAS"] = QString::number(preset.brakes.frontBrakeBias / 100.0);
    m_currentSetup["TIRE.PRESSURE_FRONT"] = QString::number(preset.tyres.frontTyrePressure[0]);
    m_currentSetup["TIRE.PRESSURE_REAR"] = QString::number(preset.tyres.rearTyrePressure[0]);
    m_currentSetup["AERO.CD"] = "0.35";
    m_frontBump = static_cast<int>(preset.suspension.frontBumpDamper[0] / 80.0);
    m_rearBump = static_cast<int>(preset.suspension.rearBumpDamper[0] / 80.0);
    m_frontRebound = m_frontBump;
    m_rearRebound = m_rearBump;
    m_frontSpring = static_cast<int>((preset.suspension.frontSpringRate[0] - 30000) / 1700.0);
    m_rearSpring = static_cast<int>((preset.suspension.rearSpringRate[0] - 30000) / 1700.0);
    m_rideHeight = static_cast<int>(preset.suspension.frontRideHeight / 1.5);
    m_frontWing = static_cast<int>(preset.aero.frontWingAngle * 5);
    m_rearWing = static_cast<int>(preset.aero.rearWingAngle * 5);
    m_preload = static_cast<int>(preset.differential.preload * 5);
    m_brakeBias = static_cast<int>((preset.brakes.frontBrakeBias - 40) * 2.5);
    m_brakePower = static_cast<int>(preset.brakes.brakePressure);
    m_isModified = true;
    emit statusMessage("Applied preset: " + name);
    emit setupLoaded();
}

void SetupEditorQmlBridge::setValue(const QString& key, const QString& value) {
    if (m_currentSetup.value(key).toString() != value) {
        m_currentSetup[key] = value;
        m_isModified = true;
        emit valueChanged(key, value);
    }
}

QString SetupEditorQmlBridge::getValue(const QString& key) const {
    return m_currentSetup.value(key).toString();
}

int SetupEditorQmlBridge::frontBump() const { return m_frontBump; }
int SetupEditorQmlBridge::rearBump() const { return m_rearBump; }
int SetupEditorQmlBridge::frontRebound() const { return m_frontRebound; }
int SetupEditorQmlBridge::rearRebound() const { return m_rearRebound; }
int SetupEditorQmlBridge::frontSpring() const { return m_frontSpring; }
int SetupEditorQmlBridge::rearSpring() const { return m_rearSpring; }
int SetupEditorQmlBridge::rideHeight() const { return m_rideHeight; }
int SetupEditorQmlBridge::frontWing() const { return m_frontWing; }
int SetupEditorQmlBridge::rearWing() const { return m_rearWing; }
int SetupEditorQmlBridge::preload() const { return m_preload; }
int SetupEditorQmlBridge::brakeBias() const { return m_brakeBias; }
int SetupEditorQmlBridge::brakePower() const { return m_brakePower; }

void SetupEditorQmlBridge::setFrontBump(int v) { if (m_frontBump != v) { m_frontBump = v; m_isModified = true; emit frontBumpChanged(); } }
void SetupEditorQmlBridge::setRearBump(int v) { if (m_rearBump != v) { m_rearBump = v; m_isModified = true; emit rearBumpChanged(); } }
void SetupEditorQmlBridge::setFrontRebound(int v) { if (m_frontRebound != v) { m_frontRebound = v; m_isModified = true; emit frontReboundChanged(); } }
void SetupEditorQmlBridge::setRearRebound(int v) { if (m_rearRebound != v) { m_rearRebound = v; m_isModified = true; emit rearReboundChanged(); } }
void SetupEditorQmlBridge::setFrontSpring(int v) { if (m_frontSpring != v) { m_frontSpring = v; m_isModified = true; emit frontSpringChanged(); } }
void SetupEditorQmlBridge::setRearSpring(int v) { if (m_rearSpring != v) { m_rearSpring = v; m_isModified = true; emit rearSpringChanged(); } }
void SetupEditorQmlBridge::setRideHeight(int v) { if (m_rideHeight != v) { m_rideHeight = v; m_isModified = true; emit rideHeightChanged(); } }
void SetupEditorQmlBridge::setFrontWing(int v) { if (m_frontWing != v) { m_frontWing = v; m_isModified = true; emit frontWingChanged(); } }
void SetupEditorQmlBridge::setRearWing(int v) { if (m_rearWing != v) { m_rearWing = v; m_isModified = true; emit rearWingChanged(); } }
void SetupEditorQmlBridge::setPreload(int v) { if (m_preload != v) { m_preload = v; m_isModified = true; emit preloadChanged(); } }
void SetupEditorQmlBridge::setBrakeBias(int v) { if (m_brakeBias != v) { m_brakeBias = v; m_isModified = true; emit brakeBiasChanged(); } }
void SetupEditorQmlBridge::setBrakePower(int v) { if (m_brakePower != v) { m_brakePower = v; m_isModified = true; emit brakePowerChanged(); } }

QVariantMap SetupEditorQmlBridge::getAllValues() const {
    return m_currentSetup;
}

bool SetupEditorQmlBridge::isModified() const {
    return m_isModified;
}

QStringList SetupEditorQmlBridge::getRecentSetups() const {
    QStringList setups;
    QDir dir(m_setupDir);
    if (dir.exists()) {
        QStringList entries = dir.entryList({"*.ini"}, QDir::Files, QDir::Time);
        for (int i = 0; i < std::min<qsizetype>(entries.size(), 20); ++i) {
            setups.append(dir.absoluteFilePath(entries[i]));
        }
    }
    return setups;
}

void SetupEditorQmlBridge::exportToCar(const QString& carName, const QString& trackName) {
    if (m_currentSetup.isEmpty()) {
        emit errorMessage("No setup to export");
        return;
    }

    QString exportPath = m_setupDir + "/" + carName + "/" + trackName;
    QDir().mkpath(exportPath);
    saveSetup(exportPath + "/setup.ini");
    emit statusMessage("Exported setup for " + carName + " at " + trackName);
}

QStringList SetupEditorQmlBridge::getSetupKeys() const {
    QStringList keys;
    QSet<QString> sections;
    for (auto it = m_currentSetup.begin(); it != m_currentSetup.end(); ++it) {
        if (it.key().contains(".")) {
            sections.insert(it.key().section(".", 0, 0));
        }
    }
    return sections.values();
}

// ============================================================================
// SetupEditorModule
// ============================================================================

SetupEditorModule::SetupEditorModule(QWidget* parent)
    : ModuleGuiBase(parent)
{
    setObjectName("SetupEditorModule");
}

bool SetupEditorModule::initialize()
{
    if (m_uiBuilt) return true;
    bool ok = ModuleGuiBase::initialize();
    syncFromBridge();
    LOG_INFO("SetupEditorModule", "Initializing Setup Editor module");
    return ok;
}

void SetupEditorModule::shutdown()
{
    ModuleGuiBase::shutdown();
    LOG_INFO("SetupEditorModule", "Shutting down Setup Editor module");
}

void SetupEditorModule::importFile(const QString& filePath)
{
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->loadSetup(filePath);
        syncFromBridge();
        logSuccess("Loaded setup: " + filePath);
    }
}

void SetupEditorModule::exportFile(const QString& filePath)
{
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->saveSetup(filePath);
        logSuccess("Saved setup: " + filePath);
    }
}

QJsonObject SetupEditorModule::serializeProject() const
{
    QJsonObject data;
    auto* bridge = SetupEditorQmlBridge::instance();
    if (bridge) {
        data["values"] = QJsonObject::fromVariantMap(bridge->getAllValues());
    }
    return data;
}

void SetupEditorModule::deserializeProject(const QJsonObject& data)
{
    if (data.contains("values")) {
        QVariantMap vals = data["values"].toObject().toVariantMap();
        if (auto* bridge = SetupEditorQmlBridge::instance()) {
            for (auto it = vals.begin(); it != vals.end(); ++it) {
                bridge->setValue(it.key(), it.value().toString());
            }
            syncFromBridge();
        }
    }
}

void SetupEditorModule::buildUI()
{
    m_tabWidget = new QTabWidget(this);
    m_tabWidget->setStyleSheet(
        "QTabWidget::pane { border: 1px solid #3a3a3a; background: #1e1e1e; }"
        "QTabBar::tab { background: #2d2d2d; color: #aaa; padding: 8px 16px; border: 1px solid #3a3a3a; border-bottom: none; }"
        "QTabBar::tab:selected { background: #3a5a8a; color: #fff; }"
        "QTabBar::tab:hover { background: #4a6a9a; }"
    );

    // Tab 1: Setup Values
    QWidget* valuesTab = new QWidget();
    {
        QVBoxLayout* layout = new QVBoxLayout(valuesTab);
        layout->setContentsMargins(8, 8, 8, 8);
        layout->setSpacing(6);

        QGroupBox* suspensionGroup = new QGroupBox("Suspension");
        QFormLayout* sform = new QFormLayout(suspensionGroup);

        m_frontBumpSpin = new QSpinBox();
        m_frontBumpSpin->setRange(0, 200);
        connect(m_frontBumpSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Front Bump:", m_frontBumpSpin);

        m_rearBumpSpin = new QSpinBox();
        m_rearBumpSpin->setRange(0, 200);
        connect(m_rearBumpSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Rear Bump:", m_rearBumpSpin);

        m_frontReboundSpin = new QSpinBox();
        m_frontReboundSpin->setRange(0, 200);
        connect(m_frontReboundSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Front Rebound:", m_frontReboundSpin);

        m_rearReboundSpin = new QSpinBox();
        m_rearReboundSpin->setRange(0, 200);
        connect(m_rearReboundSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Rear Rebound:", m_rearReboundSpin);

        m_frontSpringSpin = new QSpinBox();
        m_frontSpringSpin->setRange(0, 200);
        connect(m_frontSpringSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Front Spring Rate:", m_frontSpringSpin);

        m_rearSpringSpin = new QSpinBox();
        m_rearSpringSpin->setRange(0, 200);
        connect(m_rearSpringSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Rear Spring Rate:", m_rearSpringSpin);

        m_rideHeightSpin = new QSpinBox();
        m_rideHeightSpin->setRange(0, 200);
        connect(m_rideHeightSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        sform->addRow("Ride Height:", m_rideHeightSpin);

        layout->addWidget(suspensionGroup);

        QGroupBox* aeroGroup = new QGroupBox("Aero & Drivetrain");
        QFormLayout* aform = new QFormLayout(aeroGroup);

        m_frontWingSpin = new QSpinBox();
        m_frontWingSpin->setRange(0, 200);
        connect(m_frontWingSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        aform->addRow("Front Wing:", m_frontWingSpin);

        m_rearWingSpin = new QSpinBox();
        m_rearWingSpin->setRange(0, 200);
        connect(m_rearWingSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        aform->addRow("Rear Wing:", m_rearWingSpin);

        m_preloadSpin = new QSpinBox();
        m_preloadSpin->setRange(0, 200);
        connect(m_preloadSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        aform->addRow("Preload:", m_preloadSpin);

        m_brakeBiasSpin = new QSpinBox();
        m_brakeBiasSpin->setRange(0, 100);
        connect(m_brakeBiasSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        aform->addRow("Brake Bias (%):", m_brakeBiasSpin);

        m_brakePowerSpin = new QSpinBox();
        m_brakePowerSpin->setRange(0, 200);
        connect(m_brakePowerSpin, QOverload<int>::of(&QSpinBox::valueChanged), this, &SetupEditorModule::onValueChanged);
        aform->addRow("Brake Power:", m_brakePowerSpin);

        layout->addWidget(aeroGroup);

        QHBoxLayout* btnLayout = new QHBoxLayout();
        m_loadBtn = new QPushButton("Load Setup");
        connect(m_loadBtn, &QPushButton::clicked, this, &SetupEditorModule::onLoadSetup);
        btnLayout->addWidget(m_loadBtn);
        m_saveBtn = new QPushButton("Save Setup");
        connect(m_saveBtn, &QPushButton::clicked, this, &SetupEditorModule::onSaveSetup);
        btnLayout->addWidget(m_saveBtn);
        m_resetBtn = new QPushButton("Reset Defaults");
        connect(m_resetBtn, &QPushButton::clicked, this, &SetupEditorModule::onResetDefaults);
        btnLayout->addWidget(m_resetBtn);
        btnLayout->addStretch();
        layout->addLayout(btnLayout);

        layout->addStretch();
    }
    m_tabWidget->addTab(valuesTab, "Values");

    // Tab 2: Analysis
    QWidget* analysisTab = new QWidget();
    {
        QVBoxLayout* layout = new QVBoxLayout(analysisTab);
        layout->setContentsMargins(8, 8, 8, 8);
        layout->setSpacing(8);

        QGroupBox* telemetryGroup = new QGroupBox("Telemetry-Driven Setup Analysis");
        QVBoxLayout* tl = new QVBoxLayout(telemetryGroup);
        m_importTelemetryBtn = new QPushButton("Import Telemetry Lap");
        connect(m_importTelemetryBtn, &QPushButton::clicked, this, &SetupEditorModule::onImportTelemetry);
        tl->addWidget(m_importTelemetryBtn);
        m_analyzeBtn = new QPushButton("Analyze Setup");
        connect(m_analyzeBtn, &QPushButton::clicked, this, &SetupEditorModule::onAnalyze);
        tl->addWidget(m_analyzeBtn);
        m_analysisOutput = new QTextEdit();
        m_analysisOutput->setReadOnly(true);
        m_analysisOutput->setStyleSheet("QTextEdit { background: #0a0a0a; color: #c8c8c8; font-family: Consolas; font-size: 10px; }");
        tl->addWidget(m_analysisOutput, 1);
        layout->addWidget(telemetryGroup);

        QGroupBox* telemetryDataGroup = new QGroupBox("Telemetry Data");
        QVBoxLayout* tdl = new QVBoxLayout(telemetryDataGroup);
        m_telemetryOutput = new QTextEdit();
        m_telemetryOutput->setReadOnly(true);
        m_telemetryOutput->setStyleSheet("QTextEdit { background: #0a0a0a; color: #c8c8c8; font-family: Consolas; font-size: 10px; }");
        tdl->addWidget(m_telemetryOutput);
        layout->addWidget(telemetryDataGroup);

        layout->addStretch();
    }
    m_tabWidget->addTab(analysisTab, "Analysis");

    // Tab 3: Presets
    QWidget* presetsTab = new QWidget();
    {
        QVBoxLayout* layout = new QVBoxLayout(presetsTab);
        layout->setContentsMargins(8, 8, 8, 8);
        layout->setSpacing(8);

        QGroupBox* presetGroup = new QGroupBox("Setup Presets");
        QVBoxLayout* pl = new QVBoxLayout(presetGroup);
        m_presetList = new QListWidget();
        pl->addWidget(m_presetList);
        m_applyPresetBtn = new QPushButton("Apply Preset");
        connect(m_applyPresetBtn, &QPushButton::clicked, this, &SetupEditorModule::onApplyPreset);
        pl->addWidget(m_applyPresetBtn);
        layout->addWidget(presetGroup);

        m_statusLog = new QTextEdit();
        m_statusLog->setReadOnly(true);
        m_statusLog->setMaximumHeight(150);
        m_statusLog->setStyleSheet("QTextEdit { background: #0a0a0a; color: #c8c8c8; font-family: Consolas; font-size: 10px; }");
        layout->addWidget(m_statusLog);

        layout->addStretch();
    }
    m_tabWidget->addTab(presetsTab, "Presets");

    m_mainLayout->insertWidget(1, m_tabWidget, 1);
    m_uiBuilt = true;
}

void SetupEditorModule::syncFromBridge()
{
    auto* bridge = SetupEditorQmlBridge::instance();
    if (!bridge) return;
    m_frontBumpSpin->setValue(bridge->frontBump());
    m_rearBumpSpin->setValue(bridge->rearBump());
    m_frontReboundSpin->setValue(bridge->frontRebound());
    m_rearReboundSpin->setValue(bridge->rearRebound());
    m_frontSpringSpin->setValue(bridge->frontSpring());
    m_rearSpringSpin->setValue(bridge->rearSpring());
    m_rideHeightSpin->setValue(bridge->rideHeight());
    m_frontWingSpin->setValue(bridge->frontWing());
    m_rearWingSpin->setValue(bridge->rearWing());
    m_preloadSpin->setValue(bridge->preload());
    m_brakeBiasSpin->setValue(bridge->brakeBias());
    m_brakePowerSpin->setValue(bridge->brakePower());
}

void SetupEditorModule::syncToBridge()
{
    auto* bridge = SetupEditorQmlBridge::instance();
    if (!bridge) return;
    bridge->setFrontBump(m_frontBumpSpin->value());
    bridge->setRearBump(m_rearBumpSpin->value());
    bridge->setFrontRebound(m_frontReboundSpin->value());
    bridge->setRearRebound(m_rearReboundSpin->value());
    bridge->setFrontSpring(m_frontSpringSpin->value());
    bridge->setRearSpring(m_rearSpringSpin->value());
    bridge->setRideHeight(m_rideHeightSpin->value());
    bridge->setFrontWing(m_frontWingSpin->value());
    bridge->setRearWing(m_rearWingSpin->value());
    bridge->setPreload(m_preloadSpin->value());
    bridge->setBrakeBias(m_brakeBiasSpin->value());
    bridge->setBrakePower(m_brakePowerSpin->value());
}

void SetupEditorModule::onLoadSetup()
{
    QString path = selectFile("Load Car Setup", "INI Files (*.ini);;All Files (*)");
    if (path.isEmpty()) return;
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->loadSetup(path);
        syncFromBridge();
        logSuccess("Setup loaded: " + path);
    }
}

void SetupEditorModule::onSaveSetup()
{
    syncToBridge();
    QString path = QFileDialog::getSaveFileName(this, "Save Car Setup", QString(), "INI Files (*.ini);;All Files (*)");
    if (path.isEmpty()) return;
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->saveSetup(path);
        logSuccess("Setup saved: " + path);
    }
}

void SetupEditorModule::onResetDefaults()
{
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->resetToDefault();
        syncFromBridge();
        log("Setup reset to defaults");
    }
}

void SetupEditorModule::onApplyPreset()
{
    auto items = m_presetList->selectedItems();
    if (items.isEmpty()) return;
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->applyPreset(items[0]->text());
        syncFromBridge();
        m_statusLog->append("Applied preset: " + items[0]->text());
        logSuccess("Setup preset applied");
    }
}

void SetupEditorModule::onValueChanged()
{
    syncToBridge();
}

void SetupEditorModule::onAnalyze()
{
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        bridge->analyzeSetup();
        m_analysisOutput->clear();
        m_analysisOutput->append("Setup analysis complete.");
        log("Setup analysis performed");
    }
}

void SetupEditorModule::onImportTelemetry()
{
    QString path = selectFile("Import Telemetry Data", "JSON (*.json);;All Files (*)");
    if (path.isEmpty()) return;
    if (auto* bridge = SetupEditorQmlBridge::instance()) {
        QVariantMap analysis = bridge->importTelemetryLap(QVariantMap());
        bridge->autoOptimizeSetup();
        syncFromBridge();
        m_telemetryOutput->append("Imported telemetry: " + path);
        logSuccess("Telemetry imported and setup optimized");
    }
}

} // namespace ks